sudo: true
language: php
php:
- '7.0'
services:
- mysql
install: source <(curl -s https://raw.githubusercontent.com/falcon78921/Cardinal/master/scripts/install/travis-builder.sh)
before_script: 
- sudo cp -r * /var/www/html # Copy Cardinal contents to root of Apache2 web directory
- sudo chown -R www-data:www-data /var/www/html
- composer global require nette/code-checker
- composer update
script: php vendor/bin/nette/code-checker/code-checker -d /var/www/html
