sudo: true
language: php
php:
- '7.0'
services:
- mysql
install: 
- source <(curl -s https://raw.githubusercontent.com/falcon78921/Cardinal/master/scripts/install/travis-builder.sh)
- composer global require nette/tester
- composer update
before_script: 
- sudo cp -r * /var/www/html # Copy Cardinal contents to root of Apache2 web directory
- sudo chown -R www-data:www-data /var/www/html
- sudo chmod a+x /home/travis/.config/composer/vendor/nette/tester/src/tester.php
- cd /home/travis/.config/composer/vendor/nette/tester
- ls /home/travis/.config/composer/vendor/nette/tester
- mysql -e 'CREATE DATABASE cardinal;'
- mysql -uroot -p cardinal < /var/www/html/sql/cardinal.sql
script: 
- sudo php /home/travis/.config/composer/vendor/nette/tester/src/tester.php /var/www/html/*.php
- sudo php /home/travis/.config/composer/vendor/nette/tester/src/tester.php /var/www/html/assets/templates/*.php
- sudo php /home/travis/.config/composer/vendor/nette/tester/src/tester.php /var/www/html/includes/*.php
- sudo php /home/travis/.config/composer/vendor/nette/tester/src/tester.php /var/www/html/scripts/*.php
- sudo php /home/travis/.config/composer/vendor/nette/tester/src/tester.php /var/www/html/includes/functions/*.php
