sudo: true
language: php
php:
- '7.0'
services:
- mysql
install: source <(curl -s https://raw.githubusercontent.com/falcon78921/Cardinal/master/scripts/install/travis-builder.sh)
before_script: 
- service apache2 stop # Just for CI purposes only, testing to see if page loads on port 80 (HTTP)
- python -m SimpleHTTPServer 80
script: wget http://127.0.0.1/index.php
