dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
services:
- mysql
install:
- python3 -m pip install -r requirements.txt
before_script:
- chmod +x ci/sqltest.py
- mysql -e 'CREATE DATABASE cardinal;'
- mysql -u root --password="" cardinal < sql/cardinal.sql
- mysql -e 'SHOW TABLES from cardinal;'
- mysql -u root --password="" cardinal -e "INSERT INTO settings (settings_id,cardinal_home,scout_dir,cardinal_tftp,poll_schedule) VALUES ('1','/opt','/scout.py','/opt','2');"
script:
- flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics
- pyflakes bin/scout.py app/main.py ci/sqltest.py
- python3 ci/sqltest.py
- python3 ci/tests/qa-get-speed.py
- pyinstaller --onefile bin/scout.py
