dist: xenial
language: python
python:
- '3.6'
- '3.7'
- '3.8'
services:
- mysql
install:
- python3 -m pip install -r requirements.txt
before_script:
- chmod +x ci/tests/*.py
- mysql -e 'CREATE DATABASE cardinal;'
- mysql -u root --password="" cardinal < sql/cardinal.sql
- mysql -e 'SHOW TABLES from cardinal;'
- ls -lah
- pip install lib/.
script:
- bash ci/tests/travis-test.sh
- pyinstaller --onefile bin/scout-cli/scout-cli.py
