sudo: true
dist: xenial
language: python
python:
- '3.4'
- '3.5'
- '3.6'
services:
- mysql
install:
- sudo pip3 install pyinstaller paramiko pyflakes mysql-connector-python configparser
before_script:
- mysql -e 'CREATE DATABASE cardinal;'
- mysql -u root --password="" cardinal < sql/cardinal.sql
- mysql -e 'SHOW TABLES from cardinal;'
- mysql -u root --password="" cardinal -e "INSERT INTO settings (settings_id,cardinal_home,scout_dir,cardinal_tftp,poll_schedule) VALUES ('1','/opt','/scout.py','/opt','2');"
script:
- sudo pyflakes bin/*.py
- sudo pyflakes app/*.py
- sudo pyinstaller --onefile bin/scout.py
after_success:
- echo "Yay! Cardinal is ready for flight! :)"
