sudo: true
language: php
php:
- '7.0'
services:
- mysql
install: source <(curl -s https://raw.githubusercontent.com/falcon78921/Cardinal/master/scripts/install/travis-builder.sh)
before_script: 
- cp -r * /var/www/html
script: wget http://127.0.1.1/index.php
