sudo: true
language: php
php:
- '7.0'
services:
- mysql
install: source <(curl -s https://raw.githubusercontent.com/falcon78921/Cardinal/master/scripts/install/travis-builder.sh)
before_script: 
- ls
- pwd
- echo "WE'RE DONE" | nc -w 5 127.0.0.1 80
script: wget http://127.0.0.1/index.php
